#' @title virtualspecies_plot
#' 
#' @description Plot virtual species raster stacks
#' 
#' @param species.stack can either be a raster stack, or a named list of two raster stacks for side by side comparison
#' @param type either "richness" to plot the sum of the rasterstack, or "incidence" to plot all raster layers (species) as presences absence maps on a grid
#' 
#' @details 
#' 
#' Simple plotting functio for raster stacks.
#' If one raster stack is provided (for example generated by generate_data_virtualspecies()):
#' "richness" plots the sum of all layers (species) and "incidence" plots the prsence/absecne maps of all layers (species) on a grid.
#' If two raster stacks are provided (for example one generated by generate_data_virtualspecies() and one which was optimized through spectre):
#' "richness" plots the sum of both rasters ande the difference between both raster sums.
#' "incidence" does currently not work for two raster stacks.
#' 
#' @return rasterstack
#' @examples 
#' \dontrun{
#' ncol <- 5
#' nrow <- 5
#' gamma <- 100
#' corr_within <- 1 # strength of spatial autocorrelation within species
#' corr_among <- 1 # strength of spatial correlation among species (% of gamma)
#' beta <- 0.75  # lower beta = wider species distributions
#' 
#' # Generate species and create list of alpha diversit:
#' spp <- generate_data_virtualspecies(ncol=ncol, nrow=nrow, corr_within = corr_within, corr_among = corr_among, gamma = gamma, beta = beta)
#' 
#' # plot species distributions:
#' virtualspecies_plot(spp, type="incidence")
#' # plot alpha diversity:
#' virtualspecies_plot(spp, type="richness")
#' 
#' }
#' @export

virtualspecies_plot <- function(species.stack, type="richness")
{
  cols.incidence <- c("TRUE" = "#536E31", "FALSE" = "#D6D6CE")
  
  ## If we have only one raster stack, plot it:
  if(!is.list(species.stack))
  {
    if(type == "richness")
    {
      species.stack.sum <- raster::as.data.frame(sum(species.stack), xy=TRUE)
      
      pp <- ggplot2::ggplot(species.stack.sum, ggplot2::aes(x=x, y=y, fill=layer)) +
        ggplot2::geom_tile() +
        ggplot2::coord_equal() +
        ggplot2::guides(fill="none") +
        ggplot2::scale_fill_viridis_c(option="E") +
        ggplot2::theme_void()
      
    }
    
    if(type == "incidence")
    {
      
      pp <- purrr::map(seq(nlayers(species.stack)), function(x){
        # convert raster to df:
        species.stack.x <- raster::as.data.frame(species.stack[[x]], xy=TRUE)
        names(species.stack.x) <- c("x", "y", "z")
        species.stack.x$z <- as.logical(species.stack.x$z)
        
        p.x <- ggplot2::ggplot(species.stack.x, ggplot2::aes(x=x, y=y, fill=z)) +
          ggplot2::geom_tile() +
          ggplot2::coord_equal() +
          ggplot2::guides(fill="none") +
          ggplot2::scale_fill_manual(values=cols.incidence) +
          ggplot2::theme_void()
        return(p.x)
      }) 
      
      pp <- cowplot::plot_grid(plotlist = pp)
    }
  } else
  {
    if(length(species.stack) != 2) {
      stop("Only two elements can be used for plotting!")
    }
    if(nlayers(species.stack[[1]]) != nlayers(species.stack[[2]])) {
      stop("Please provide a list with two raster stacks of equal size!")
    }
    
    ## Plot both in comparison:
    if(type == "richness")
    {
      ## Calculate richness of both datasets:
      species.stack.sum.1 <- raster::as.data.frame(sum(species.stack[[1]]), xy=TRUE)
      species.stack.sum.1$name=names(species.stack)[1]
      species.stack.sum.2 <- raster::as.data.frame(sum(species.stack[[2]]), xy=TRUE)
      species.stack.sum.2$name=names(species.stack)[2]
      
      ## calculate difference:
      species.stack.diff <- merge(species.stack.sum.1, species.stack.sum.2, by=c("x", "y"))
      species.stack.diff$layer <- species.stack.diff$layer.x - species.stack.diff$layer.y
      species.stack.diff <- species.stack.diff[c("x", "y", "layer")]
      species.stack.diff$name <- "difference"
      
      ## Put everything together:
      species.stack.sum <- rbind(species.stack.sum.1, species.stack.sum.2, species.stack.diff)
      species.stack.sum$name <- factor(species.stack.sum$name, levels=c(names(species.stack), "difference"))
      
      pp <- ggplot2::ggplot(species.stack.sum, ggplot2::aes(x=x, y=y, fill=layer)) +
        ggplot2::facet_wrap(~name) +
        ggplot2::geom_tile() +
        ggplot2::coord_equal() +
        ggplot2::guides(fill="none") +
        ggplot2::scale_fill_viridis_c(option="E") +
        ggplot2::theme_void()
      
    }
    if(type == "incidence")
    {
      print("not yet implemented")
      
    }
  }
  
  return(pp)
}
